"""added vote_type to PostVote

Revision ID: 7e25620d5c42
Revises: f5163fdca19c
Create Date: 2026-02-02 06:42:25.234070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e25620d5c42'
down_revision = 'f5163fdca19c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_post', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    with op.batch_alter_table('post_vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vote_type', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_vote', schema=None) as batch_op:
        batch_op.drop_column('vote_type')

    with op.batch_alter_table('forum_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
