"""added participation fields

Revision ID: f5163fdca19c
Revises: 
Create Date: 2026-02-02 04:20:01.086231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5163fdca19c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('contact_number', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('purpose', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participation', schema=None) as batch_op:
        batch_op.drop_column('purpose')
        batch_op.drop_column('email')
        batch_op.drop_column('contact_number')
        batch_op.drop_column('address')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
